name: 3.1.workflow_dispatch.yaml
on:
  workflow_dispatch:
    inputs:
      username:
        description: "username of the user"
        required: true
        type: string
      level:
        description: "level of the user"
        required: true
        type: int
      class:
        description: "class of the user"
        required: true
        default: "jedi"
        type: choice
        options:
          - "jedi"
          - "sith"
          - "rebel"
jobs:
  player_infos:
    runs-on: ubuntu-latest
    steps:
      - name: Show the player details
        run: |
          echo "Le joueur ${{ github.event.inputs.username }} est de niveau ${{ github.event.inputs.level }} et joue un ${{ github.event.inputs.class }}."
