name: 3.2.workflow_regulier.yaml
on: 
  schedule: 
  - cron: '*/10 * * * *' 
  - cron: '0 0 1 * *' 
jobs: 
  say_hello: 
    runs-on: 
    windows-latest steps: 
    - name: Afficher le message Hello, world! 
      run: echo "Hello, world!"