name: 3.4.action_checkout
on:
  push:
jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest #a définir à l'échelle du job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup_python@v3.10
      - run: |
          python main.py
