name: 4.2.confidential_data.yaml
on:
  push:
jobs:
  confidential_data:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher la valeur du secret
        run: echo "La valeur de SUPER_SECRET est ${{ secrets.SUPER_SECRET }}"