name: 5.2.log_group.yaml
on:
  push:
jobs:
  log_group:
    runs-on: ubuntu-latest 
    steps:
      - name: Create log group
        run: |
          echo "::group::ecole-it"
          echo "hello, ecole-it"
          echo "::endgroup::"
          echo "This is not in the group"